name: "Check Terraform Module versions"
description: >
  Check Terraform Module versions in each file and compare with 
  the latest version available in the Terraform Registry.

runs: 
  using: composite
  steps:
  - name: Run
    run: |
      export WORKING_DIRECTORY=${{ github.workspace }}
      cd ${{ github.action_path }}
      go run main.go
    shell: bash
