name: "Check Terraform Module versions"
description: >
  Check Terraform Module versions in each file and compare with 
  the latest version available in the Terraform Registry.

runs: 
  using: composite
  steps:
  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}
  - name: Run
    run: |
      cd ${{ github.action_path }}
      pwd
      ls -la
      go run main.go
    shell: bash
